---
# Настройки Kubernetes
kubernetes_version: "1.25"
cgroup_driver: systemd
network_plugin: flannel
pod_network_cidr: 10.244.0.0/16
service_cidr: 10.96.0.0/12

# Настройки узлов
node_type: "standard-v2"
disk_size: 64
disk_type: "network-ssd"

# Пакеты Kubernetes
k8s_packages:
  - kubelet={{ kubernetes_version }}-00
  - kubeadm={{ kubernetes_version }}-00
  - kubectl={{ kubernetes_version }}-00
