---
# Настройки сервера srv
каталог_проектов: /opt/projects
каталог_логов: /var/log/apps
каталог_бэкапов: /opt/backups
каталог_скриптов: /opt/scripts

# Настройки мониторинга
каталог_мониторинга: /opt/monitoring
порт_grafana: 3000
порт_prometheus: 9090
порт_node_exporter: 9100

# Настройки CI/CD
каталог_артефактов: /opt/ci-cd/artefacts
пользователь_ci_cd: runner
группа_ci_cd: runner
квота_диска_мягкая: 10G
квота_диска_жесткая: 12G
